version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/conference?authSource=admin
    depends_on:
      - mongodb

  wserver:
    build:
      context: ./wserver
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - ./wserver:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000

volumes:
  mongodb_data: